package names

const DATABASE_BRANCH_NAME = "branchdb"
const DATABASE_BRANCH_VALUE = DATABASE_BRANCH_NAME + "/values.yaml"

const DATABASE_CART_NAME = "cartdb"
const DATABASE_CART_VALUE = DATABASE_CART_NAME + "/values.yaml"

const DATABASE_CATALOG_NAME = "catalogdb"
const DATABASE_CATALOG_VALUE = DATABASE_CATALOG_NAME + "/values.yaml"

const DATABASE_CHAT_NAME = "chatdb"
const DATABASE_CHAT_VALUE = DATABASE_CHAT_NAME + "/values.yaml"

const DATABASE_CHIPMUNK_NAME = ""
const DATABASE_CHIPMUNK_VALUES = ""

const DATABASE_DYMO_NAME = ""
const DATABASE_DYMO_VALUES = ""

const DATABASE_GATEKEEPER_NAME = "gatekeeperdb"
const DATABASE_GATEKEEPER_VALUE = DATABASE_GATEKEEPER_NAME + "/values.yaml"

const DATABASE_PAYMENT_NAME = "paymentdb"
const DATABASE_PAYMENT_VALUES = DATABASE_PAYMENT_NAME + "/values.yaml"

const DATABASE_XPRESS_NAME = "xpressdb"
const DATABASE_XPRESS_VALUE = DATABASE_XPRESS_NAME + "/values.yaml"

const DATABASE_XTRACK_NAME = ""
const DATABASE_XTRACK_VALUE = ""