package names

const ELASTICSEARCH_VERSION = "7.9.1"
const ELASTICSEARCH_DEPLOYMENT_NAME = "elasticsearch"
const ELASTICSEARCH_DEPLOYMENT_DIR = "elasticsearch"
const ELASTICSEARCH_DEPLOYMENT_VALUE = ELASTICSEARCH_DEPLOYMENT_DIR + "/values.yaml"
const ELASTICSEARCH_DEPLOYMENT_LOCAL_STORAGE_VALUE = ELASTICSEARCH_DEPLOYMENT_DIR + "/local-path-storage.yaml"

const LOGSTASH_DEPLOYMENT_VERSION = "7.9.1"
const LOGSTASH_DEPLOYMENT_NAME = "logstash"
const LOGSTASH_DEPLOYMENT_DIR = "logstash"
const LOGSTASH_DEPLOYMENT_VALUE = LOGSTASH_DEPLOYMENT_DIR + "/values.yaml"

const KIBANA_DEPLOYMENT_VERSION = "7.9.1"
const KIBANA_DEPLOYMENT_NAME = "kibana"
const KIBANA_DEPLOYMENT_DIR = "kibana"

const RABBITMQ_NAME = "rabbitmq"