package names

var REPO_LIST = []string{
	"https://github.com/Guya-LTD/guya.git",
	"https://github.com/Guya-LTD/bits.git",
	"https://github.com/Guya-LTD/gxdriver.git",
	"https://github.com/Guya-LTD/user.git",
	"https://github.com/Guya-LTD/gatekeeper.git",
	"https://github.com/Guya-LTD/catalog.git",
	"https://github.com/Guya-LTD/dymo.git",
	"https://github.com/Guya-LTD/gcss.git",
	"https://github.com/Guya-LTD/xpress.git",
	"https://github.com/Guya-LTD/branch.git",
	"https://github.com/Guya-LTD/chipmunk.git",
	"https://github.com/Guya-LTD/postgres.git",
	"https://github.com/Guya-LTD/shop-web.git",
	"https://github.com/Guya-LTD/xpress-web.git",
	"https://github.com/Guya-LTD/nginx.git",
	"https://github.com/Guya-LTD/redis.git",
	"https://github.com/Guya-LTD/refme.git",
	"https://github.com/Guya-LTD/xtrack.git",
	"https://github.com/Guya-LTD/admin-panel.git",
	"https://github.com/Guya-LTD/alfa-geez-node.git",
	"https://github.com/Guya-LTD/chat.git",
	"https://github.com/Guya-LTD/cart.git",
	"https://github.com/Guya-LTD/pyrat.git",
	"https://github.com/Guya-LTD/payment.git",
	"https://github.com/Guya-LTD/storybook.git",
	"https://github.com/Guya-LTD/python-logstash.git",
	"https://github.com/Guya-LTD/gcli.git",
	"https://github.com/Guya-LTD/srs.git",
}